config/routes.rb
Rails.application.routes.draw do
  get 'logins/new'

  get 'logins/create'

  get 'logins/destroy'

  get 'login/new'

  get 'login/create'

  get 'login/destroy'

  get '/home', to: 'pages#home'

  root 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new]

  get '/register', to: 'chefs#new'

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get '/logout', to: 'logins#destroy' 

end

app/models/chef.rb
class Chef < ActiveRecord::Base
	has_many :recipes
	has_many :likes
	validates :chefname, presence: true, length: {minimum: 3, maximum: 40}
	VALID_EMAIL_REGEX = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
	has_secure_password
	validates :email, presence: true, length: {maximum: 105}, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX}


end

app/models/like.rb
class Like < ActiveRecord::Base

belongs_to :chef
belongs_to :recipe

validates_uniqueness_of :chef, scope: :recipe


end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :chef
	has_many :likes
	validates :name, presence: true, length: {minimum: 5, maximum: 100}
	validates :summary, presence: true, length: {minimum: 10, maximum: 150}
	validates :description, presence: true, length: {minimum: 20 , maximum: 500}
	validates :chef_id, presence: true
	mount_uploader :picture, PictureUploader
	validate :picture_size
	default_scope ->  {order(updated_at: :desc)}

	def thumbs_up_total
		self.likes.where(like: true).size
	end

	def thumbs_down_total
		self.likes.where(like: false).size
	end


	private
	def picture_size
		if picture.size > 5.megabytes
			errors.add(:picture, "should be less than 5MB")
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
  	!!current_user
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

	def new
		@chef = Chef.new
	end

	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 3)
	end

	def create
		@chef = Chef.new(chef_params)
		if @chef.save
			flash[:success] = "Account Created!"
			session[:chef_id] = @chef.id
			redirect_to recipes_path
		else
			render 'new'
		end
	end


	def edit
		@chef = Chef.find(params[:id])
		if !logged_in? || @chef != current_user
			flash[:danger] = "You can only edit your own profile. Login to continue"
			redirect_to recipes_path
		end
	end

	def update
		@chef = Chef.find(params[:id])
		if @chef == current_user && logged_in?	
			if @chef.update(chef_params)
				flash[:success] = "Account Updated"
				redirect_to recipes_path
			else
				render :edit
			end
		else
			flash[:danger] = "Please login to update your profile"
			redirect_to recipes_path
		end
	end

	def show
		@chef = Chef.find(params[:id])
		@recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
	end


	private
	def chef_params
		params.require(:chef).permit(:chefname, :email, :password)
	end


end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
  	chef = Chef.find_by(email: params[:email])
  	if chef && chef.authenticate(params[:password])
  		session[:chef_id] = chef.id
  		flash[:success] = "You are logged in"
  		redirect_to recipes_path
  	else
  		flash.now[:danger] = "Email or Password is not correct"
  		render 'new'
  	end
  end

  def destroy
  	session[:chef_id] = nil
  	flash[:success] = "You have logged out"
  	redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to recipes_path if logged_in?
	end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

def index
	@recipes = Recipe.paginate(page: params[:page], per_page: 2)
	respond_to do |format|
		format.html
		format.json { render json: @recipes}
	end
end

def show
	@recipe = Recipe.find(params[:id])
	@chef = @recipe.chef
	respond_to do |format|
		format.html
		format.json { render json: @recipe }
	end
end

def new
	@recipe = Recipe.new
	if !logged_in?
		redirect_to recipes_path
		flash[:warning] = "Log in to create a recipe"
	end
end

def create
	@recipe = Recipe.new(recipe_params)
	@recipe.chef = current_user
	if logged_in?
		if @recipe.save
			flash[:success] = "Your recipe was saved!"
			redirect_to recipes_path
		else	
			render :new
		end
	else
		flash[:danger] = "You need to login to create a recipe"
		redirect_to recipes_path
	end
end

def edit
		@recipe = Recipe.find(params[:id])
	if !logged_in? || @recipe.chef != current_user
		flash[:danger] = "You are not allowed to edit this recipe"
		redirect_to recipe_path(@recipe)
	end
end

def update
	@recipe = Recipe.find(params[:id])
	if logged_in? && @recipe.chef == current_user
		if @recipe.update(recipe_params)
			flash[:success] = "Your recipe was updated successfully"
			redirect_to recipe_path(@recipe)
		else
			render :edit
		end
	else
		flash[:danger] = "Could not update recipe. Please login"
		redirect_to recipe_path(@recipe)
	end
end

def like
	if logged_in?	
		@recipe = Recipe.find(params[:id])
		newlike = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
		if newlike.valid?
			if (newlike.like == true)
				flash[:success] = "You liked this recipe!"
			else
				flash[:success] = "You disliked this recipe!"
			end
		else
			flash[:danger] = "You can only like/dislike a recipe once"
		end
	else
		flash[:danger] = "You need to login to like a recipe"
	end
		redirect_to :back

end

private 

	def recipe_params
		params.require(:recipe).permit(:name, :summary, :description, :picture)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(chef, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
	end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>
<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for @chef do |f| %>
			<%= f.label :chefname %>
			<%= f.text_field :chefname %>

			<%= f.label :email %>
			<%= f.email_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>


			<%= f.submit(@chef.new_record? ? 'Create Account' : 'Update Account', class: "btn btn-success") %>
		<% end %>
	</div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit Your Account" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>

<ul class="nav nav-tabs">
	<li>
		<%= link_to "Recipes", recipes_path %>
	</li>
	<li class="active">
		<%= link_to "Chefs", chefs_path %>
	</li>
</ul>


<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= will_paginate %>
	</div>
</div>




<div class="row">
	<% @chefs.each do |chef| %>
	<div class="col-md-4 col-md-offset-4 center">

		<section class="chef_info center">
			<%= link_to gravatar_for(chef, size: 100), chef_path(chef) %>
			<p>
			<h5>Chef name: <%= chef.chefname %><h5>
			</p>
		</section>
	
</div>
<% end %>
</div>
	</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Create Your Account" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef: " + (@chef.chefname).titleize %>


<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
			<%= gravatar_for @chef, size: 200 %>
			<hr/>
	</div>
</div>
<% if @recipes.count > 0 %>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<p>
			<h1>Recipes:</h1>
			
			<%= will_paginate @recipes %>
		</p>
	</div>
</div>	

<% @recipes.each do |recipe| %>
	<div class="col-lg-6 well col-lg-offset-3">
		<h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
		<p><%= recipe.summary %></p>

		<p>
			<span class='quiet'><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
		</p>
	<div class="pull-right">
	<%= link_to like_recipe_path(recipe, like: true), method: :post do  %>
	<span class="glyphicon glyphicon-thumbs-up"></span>&nbsp <%= recipe.thumbs_up_total if recipe.thumbs_up_total > 0  %>
	<% end %> &nbsp&nbsp&nbsp&nbsp

	<%= link_to like_recipe_path(recipe, like: false), method: :post do  %>
	<span class="glyphicon glyphicon-thumbs-down"></span>&nbsp <%= recipe.thumbs_down_total if recipe.thumbs_down_total > 0 %>
	
	<% end %>
	</div>

	</div>

<% end %>
<% else %>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<p>
			<h1>Recipes:</h1>
			
			<h2>No recipes added</h2>
		</p>
	</div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<div class="footer">
	<p>MyRecipes</p>
</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %>
				<a class="close" data-dismiss="alert">&#215;</a>
			</div>
		<% end %>

	</div>
</div>

app/views/layouts/_navigation.html.erb
	<header class="navbar navbar-fixed-top navbar-default">
		<div class="container">
			<%= link_to 'myRecipes', root_path, class: "btn btn-lg btn-success", id: "logo" %>
			<div class="nav_item">
				<%= link_to 'View Chefs', chefs_path, class: "btn btn-default btn-warning" %>
			</div>
			<div class="nav_item">
				<%= link_to 'link2', "", class: "btn btn-default btn-warning" %>
			</div>
			<% if logged_in? %>
			<div class="nav_item">
				<%= link_to 'New Recipe', new_recipe_path, class: "btn btn-default btn-warning" %>
			</div>
			<ul class="nav_item">
				<li class="dropdown">
					<%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
					<%= current_user.chefname %> <b class="caret"></b>
					<% end %>
					<ul class="dropdown-menu">
						<li><%= link_to "View Profile", chef_path(current_user) %></li>
						<li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
						<li class="divider"></li>
						<li><%= link_to "Logout", logout_path %></li>
					</ul>
				</li>
			</ul>
			<% else %>
			<div class="nav_item">
				<%= link_to 'Log In', login_path, class: "btn btn-default btn-success" %>
			</div>
			<% end %>

		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navigation" %>

<div class="container">
	<%= render 'layouts/messages' %>

<%= yield %>

</div>





</body>
<%= render "layouts/footer" %>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/destroy.html.erb
<h1>Logins#destroy</h1>
<p>Find me in app/views/logins/destroy.html.erb</p>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Login In' %>

<div class="row">
	<div class="well col-md-6 col-md-offset-3">
		<%= form_tag '/login' do %>

			<%= label_tag :email %>
			<%= text_field_tag :email %>

			<%= label_tag :password %>
			<%= password_field_tag :password %>

			<%= submit_tag 'Login', class: 'btn btn-success' %>

		<% end %>

	</div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to MyRecipes</h1>

	<h2>Here you will find the tastiest recipes available</h2>


<%= link_to "Sign up", register_path, class: "btn btn-lg btn-success" %>

</div>

<div class="row">
	<div class="col-lg-4">
		<h3 class="midrow">
			View Recipes as Guest User
		</h3>
		<h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
		<p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %>
	</div>
	<div class="col-lg-4">
		<h3 class="midrow">
			Create an account
		</h3>
		<h2 class="left">Submit recipes and review other recipes. Its free!</h2>
		<p><%= link_to "Create Your Account", register_path, class: "btn btn-warning btn-small" %>
	</div>
	<div class="col-lg-4">
		<h3 class="midrow">
			View Recipes as Guest User
		</h3>
		<h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
		<p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %>
	</div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
	<div class="well col-md-8 col-md-offset-2">
		<%= form_for(@recipe, html: { multipart: true }) do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :summary %>
			<%= f.text_field :summary %>

			<%= f.label :descriptiom %>
			<%= f.text_area :description, rows: 10 %>

			<span class="picture">
				<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
			</span>

			<%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Update Recipe', class: "btn btn-success") %>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	$('#recipe_picture').bind('change', function() {

		size_in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 5) {

			alert('Maximum file size is 5MB. Please choose a smaller file')

		}

	});
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>


<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
	<li class="active">
		<%= link_to "Recipes", recipes_path %>
	</li>
	<li>
		<%= link_to "Chefs", chefs_path %>
	</li>
</ul>

<%= will_paginate %>
<% @recipes.each do |recipe| %>

<div class="row">

	<div class="col-md-2">

		<section class="chef_info center">
			<%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
			<h5>Chef name: <%= recipe.chef.chefname %><h5>
		</section>

	</div>
	<div class="col-lg-6 well">
		<h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
		<p><%= recipe.summary %></p>

		<p>
			<span class='quiet'><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
		</p>
								<div class="pull-right">
					<%= link_to like_recipe_path(recipe, like: true), method: :post do  %>
						<span class="glyphicon glyphicon-thumbs-up"></span>&nbsp <%= recipe.thumbs_up_total if recipe.thumbs_up_total > 0  %>
						<% end %> &nbsp&nbsp&nbsp&nbsp

					<%= link_to like_recipe_path(recipe, like: false), method: :post do  %>
						<span class="glyphicon glyphicon-thumbs-down"></span>&nbsp <%= recipe.thumbs_down_total if recipe.thumbs_down_total > 0 %>
						<% end %>
				</div>
	</div>
	<div class="col-md-4">
		<%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
	</div>
</div>
<hr/>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "New Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
	<div class="col-md-4 pull-right center">
		<%= link_to (gravatar_for @recipe.chef, size: 200), chef_path(@chef) %>
		<p>
			<h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
		</p>
	</div>
		<div class="col-md-8">
			<% if logged_in? && @recipe.chef == current_user %>
			<%= link_to 'Edit Recipe', edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
			<% end %>
			<h3><%= @recipe.summary %></h3>
			<div class="show_recipe">
				<%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
			</div>
			<div class="well">
				<p><strong>Steps:</strong></p><%= simple_format(@recipe.description) %>
				<div class="pull-right">
					<%= link_to like_recipe_path(@recipe, like: true), method: :post do  %>
						<span class="glyphicon glyphicon-thumbs-up"></span>&nbsp <%= @recipe.thumbs_up_total if @recipe.thumbs_up_total > 0  %>
						<% end %> &nbsp&nbsp&nbsp&nbsp

					<%= link_to like_recipe_path(@recipe, like: false), method: :post do  %>
						<span class="glyphicon glyphicon-thumbs-down"></span>&nbsp <%= @recipe.thumbs_down_total if @recipe.thumbs_down_total > 0 %>
						<% end %>
				</div>
			</div>
		</div>
</div>

<h5><%= link_to 'Return to Recipes Listing', recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="alert alert-danger col-md-8 col-md-offset-2">
			<h5>Please correct the following errors:</h5>

			<ul>
				<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
	<h1><%= title %></h1>
	<hr/>
</p>